version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./world:/minecraft/world
      - ./logs:/minecraft/logs
      - ./plugins:/minecraft/plugins
      - ./config:/minecraft/config
    environment:
      - MEMORY_SIZE=4608M
    restart: unless-stopped
    mem_limit: 5g
    mem_reservation: 4g
    stdin_open: true
    tty: true
